// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.11.4
// source: github.com/blueseller/deploy/api/agent/heartbeat/v1/heartbeat.proto

package heartbeat

import (
	context "context"
	types "github.com/blueseller/deploy/api/agent/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartBeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentId   *types.AgentId `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ConnectID int64          `protobuf:"varint,2,opt,name=connectID,proto3" json:"connectID,omitempty"`
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeat) GetAgentId() *types.AgentId {
	if x != nil {
		return x.AgentId
	}
	return nil
}

func (x *HeartBeat) GetConnectID() int64 {
	if x != nil {
		return x.ConnectID
	}
	return 0
}

var File_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto protoreflect.FileDescriptor

var file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDesc = []byte{
	0x0a, 0x43, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x75,
	0x65, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65,
	0x61, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x1a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x75,
	0x65, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5a, 0x0a, 0x09, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x12, 0x2f, 0x0a, 0x08, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x49, 0x44, 0x32, 0x4f, 0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x53, 0x65, 0x72, 0x69, 0x76, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x4c, 0x69, 0x76, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x14, 0x2e, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61, 0x74, 0x1a, 0x14, 0x2e, 0x68, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x42, 0x65, 0x61,
	0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x6c, 0x75, 0x65, 0x73, 0x65, 0x6c, 0x6c, 0x65, 0x72,
	0x2f, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x2f, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x2f, 0x76, 0x31, 0x3b, 0x68,
	0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescOnce sync.Once
	file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescData = file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDesc
)

func file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescGZIP() []byte {
	file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescOnce.Do(func() {
		file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescData)
	})
	return file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDescData
}

var file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_goTypes = []interface{}{
	(*HeartBeat)(nil),     // 0: heartbeat.HeartBeat
	(*types.AgentId)(nil), // 1: agent.types.AgentId
}
var file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_depIdxs = []int32{
	1, // 0: heartbeat.HeartBeat.agent_id:type_name -> agent.types.AgentId
	0, // 1: heartbeat.MonitorSerivce.LiveState:input_type -> heartbeat.HeartBeat
	0, // 2: heartbeat.MonitorSerivce.LiveState:output_type -> heartbeat.HeartBeat
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_init() }
func file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_init() {
	if File_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartBeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_goTypes,
		DependencyIndexes: file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_depIdxs,
		MessageInfos:      file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_msgTypes,
	}.Build()
	File_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto = out.File
	file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_rawDesc = nil
	file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_goTypes = nil
	file_github_com_blueseller_deploy_api_agent_heartbeat_v1_heartbeat_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MonitorSerivceClient is the client API for MonitorSerivce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorSerivceClient interface {
	LiveState(ctx context.Context, opts ...grpc.CallOption) (MonitorSerivce_LiveStateClient, error)
}

type monitorSerivceClient struct {
	cc grpc.ClientConnInterface
}

func NewMonitorSerivceClient(cc grpc.ClientConnInterface) MonitorSerivceClient {
	return &monitorSerivceClient{cc}
}

func (c *monitorSerivceClient) LiveState(ctx context.Context, opts ...grpc.CallOption) (MonitorSerivce_LiveStateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MonitorSerivce_serviceDesc.Streams[0], "/heartbeat.MonitorSerivce/LiveState", opts...)
	if err != nil {
		return nil, err
	}
	x := &monitorSerivceLiveStateClient{stream}
	return x, nil
}

type MonitorSerivce_LiveStateClient interface {
	Send(*HeartBeat) error
	Recv() (*HeartBeat, error)
	grpc.ClientStream
}

type monitorSerivceLiveStateClient struct {
	grpc.ClientStream
}

func (x *monitorSerivceLiveStateClient) Send(m *HeartBeat) error {
	return x.ClientStream.SendMsg(m)
}

func (x *monitorSerivceLiveStateClient) Recv() (*HeartBeat, error) {
	m := new(HeartBeat)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MonitorSerivceServer is the server API for MonitorSerivce service.
type MonitorSerivceServer interface {
	LiveState(MonitorSerivce_LiveStateServer) error
}

// UnimplementedMonitorSerivceServer can be embedded to have forward compatible implementations.
type UnimplementedMonitorSerivceServer struct {
}

func (*UnimplementedMonitorSerivceServer) LiveState(MonitorSerivce_LiveStateServer) error {
	return status.Errorf(codes.Unimplemented, "method LiveState not implemented")
}

func RegisterMonitorSerivceServer(s *grpc.Server, srv MonitorSerivceServer) {
	s.RegisterService(&_MonitorSerivce_serviceDesc, srv)
}

func _MonitorSerivce_LiveState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MonitorSerivceServer).LiveState(&monitorSerivceLiveStateServer{stream})
}

type MonitorSerivce_LiveStateServer interface {
	Send(*HeartBeat) error
	Recv() (*HeartBeat, error)
	grpc.ServerStream
}

type monitorSerivceLiveStateServer struct {
	grpc.ServerStream
}

func (x *monitorSerivceLiveStateServer) Send(m *HeartBeat) error {
	return x.ServerStream.SendMsg(m)
}

func (x *monitorSerivceLiveStateServer) Recv() (*HeartBeat, error) {
	m := new(HeartBeat)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MonitorSerivce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "heartbeat.MonitorSerivce",
	HandlerType: (*MonitorSerivceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LiveState",
			Handler:       _MonitorSerivce_LiveState_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "github.com/blueseller/deploy/api/agent/heartbeat/v1/heartbeat.proto",
}
